### ISSUE TITLE
範例配置不起作用

### ISSUE THREAD

**Issue by StarskyXIII** [3093FengMing/VaultPatcher#1]
不好意思打擾了，
我依照示例將以下這串貼在 config.json 中
```
{
  "target_class": {
    "name": "net.minecraft.client.gui.screens.TitleScreen",
    "mapping": "SRG",
    "stack_depth": 2
  },
  "key": "Copyright Mojang AB. Do not distribute!",
  "value": "Mojang AB."
}
```
重啟遊戲後並沒有看到任何變化，是還需要其他步驟嗎？

附上 log
https://mclo.gs/afAKcOd

**Comment by 3093FengMing** [comment]
其实是target_class的问题，stack_depth=2是我乱写的（实际情况并不是这样）
应改为
```
{
  "target_class": {
    "name": "",
    "mapping": "SRG",
    "stack_depth":0
  },
  "key": "Copyright Mojang AB. Do not distribute!",
  "value": "Mojang AB."
}
```
很抱歉示例配置错误

**Comment by 3093FengMing** [comment]
target_class.stack_depth的测定有些困难，所以不建议去使用，我会在往后的版本中新增快速导出功能

**Comment by StarskyXIII** [comment]
順便想請問一下
這模組適用於其他模組物品的工具提示嗎

像這種
![image](https://user-images.githubusercontent.com/71606873/209964134-7e44e577-9d51-4f6b-8dbc-6df5f1c8ec28.png)

**Comment by 3093FengMing** [comment]
这种是适用的，通常适用于物品名称，物品Lore（tooltip），和部分GUI字符串

**Comment by StarskyXIII** [comment]
> 其实是target_class的问题，stack_depth=2是我乱写的（实际情况并不是这样） 应改为
> 
> ```
> {
>   "target_class": {
>     "name": "",
>     "mapping": "SRG",
>     "stack_depth":0
>   },
>   "key": "Copyright Mojang AB. Do not distribute!",
>   "value": "Mojang AB."
> }
> ```
> 
> 很抱歉示例配置错误

非常抱歉，我用了之後看起來還是沒有變化，是我少做了什麼嗎？
![image](https://user-images.githubusercontent.com/71606873/209965314-8404fccd-592b-4f48-853c-9be064f7896a.png)

**Comment by 3093FengMing** [comment]
试着将stack_depth改为-1

**Comment by StarskyXIII** [comment]
> 试着将stack_depth改为-1

一樣沒有效果

**Comment by 3093FengMing** [comment]
尝试使用新版本1.2.4

**Comment by StarskyXIII** [comment]
成功了！
謝謝你們，我的超人！
