### ISSUE TITLE
[BUG] 导致文字格式缺失

### ISSUE THREAD

**Issue by DrIceTea123** [3093FengMing/VaultPatcher#4]
bug概述：安装VaultPatcher后，导致其他mod和原版内容中的文字格式（颜色、加粗等）消失。
游戏版本：1.18.2 forge 40.1.93
详细说明：
使用VaultPatcher汉化`Vault Hunters 3rd Edition - Update 6`时发现。

下图为**未安装VaultPatcher**时的物品表现：
1. `The Vault`mod内物品
<img width="962" alt="屏幕截图 2023-01-24 190909" src="https://user-images.githubusercontent.com/111784151/214283787-ff4d96ea-8003-4bb5-933d-c820512069da.png">
<img width="962" alt="屏幕截图 2023-01-24 190923" src="https://user-images.githubusercontent.com/111784151/214283820-c87ccf19-571c-445c-967e-589fbf2fa8c1.png">
2. `Applied Energetic 2`mod内物品
<img width="962" alt="屏幕截图 2023-01-24 191010" src="https://user-images.githubusercontent.com/111784151/214283979-92077892-5a68-4fce-92c2-c80646a0d8d9.png">
3.原版物品
<img width="962" alt="屏幕截图 2023-01-24 190952" src="https://user-images.githubusercontent.com/111784151/214284009-3bddc966-b387-4827-a202-dda77a0dba0d.png">

下图为**安装了VaultPatcher，未使用任何模块配置文件**时的物品表现：
1. `The Vault`mod内物品——**颜色消失**
<img width="961" alt="屏幕截图 2023-01-24 185749" src="https://user-images.githubusercontent.com/111784151/214284214-3a68a5cd-5525-4a2c-af86-95b0d3e3ecee.png">
<img width="961" alt="屏幕截图 2023-01-24 185846" src="https://user-images.githubusercontent.com/111784151/214284244-29d11c42-f269-44e5-9ee4-1773e1bd5cff.png">
2. `Applied Energetic 2`mod内物品——**颜色消失**
<img width="961" alt="屏幕截图 2023-01-24 191957" src="https://user-images.githubusercontent.com/111784151/214284313-2934bdd1-6f86-4d5d-b604-c307e381549a.png">
3. 原版物品——**颜色消失**
<img width="961" alt="屏幕截图 2023-01-24 191942" src="https://user-images.githubusercontent.com/111784151/214284353-3f71f24f-355c-42a5-bf77-8d3edf0fa478.png">

下图为**安装了VaultPatcher，使用模块配置文件，在语言文件内添加格式代码**后的物品表现：
<img width="961" alt="屏幕截图 2023-01-24 193008" src="https://user-images.githubusercontent.com/111784151/214284688-e8d95abf-d97d-48ad-be09-ff71787ab658.png">
（语言文件内对应行： `"tooltip.the_vault_patcher.mote_purity": "§b随机移除宝库水晶上的一个诅咒。",`）
——如图，是**可以使用格式化代码**的。

下图为**未安装其他任何mod，仅安装VaultPatcher**时的物品表现：
原版物品：下界之星——**颜色消失**
<img width="961" alt="屏幕截图 2023-01-24 193852" src="https://user-images.githubusercontent.com/111784151/214284952-ebcce063-abf3-41e0-a5ea-701a08820b85.png">
同时还发现，当使用`Ctrl+F`的高级提示框时，提示物品键名的文字原本为淡灰色，此处也变成了白色。

问题来源：未知

**Comment by KlparetlR** [comment]
您好，模组的使用者，有件不幸的事通知您：我已经对VH3的6.0版本的核心模组进行了硬编码提取，现在在Crowdin给vm汉化组进行汉化（所以有组长的受权），这里是链接（ https://crowdin.com/project/bzlrlang/），您可以选择继续硬编码汉化，但这一定会形成重复劳动的。

**Comment by DrIceTea123** [comment]
这里只是一个bug报告，希望作者能将该问题修复，以便使用该模组进行更多的硬编码汉化
至于我自己的工作只不过是在VM完成之前为我自己的游戏小组提供快捷且尽量完整的汉化，毕竟我们的游戏不可能等待vm完成再继续，这无关紧要

**Comment by 3093FengMing** [comment]
fix in 1.2.7

**Comment by 3093FengMing** [comment]
诱发原因为：new一个新的TextComponent时未复制Style，而导致新的TextComponent不存在原Style（包含颜色和加粗等内容）

**Comment by DrIceTea123** [comment]
1.2.7未发现该bug，已解决
