### ISSUE TITLE
forge-1.2.8+1.18.2 附魔等级和装备伤害信息不显示

### ISSUE THREAD

**Issue by cnmdzsf** [3093FengMing/VaultPatcher#5]
mc 1.18.2版本,只安装forge最新版和jei，未修改配置文件

1.2.8版本原版装备伤害信息不显示（1.2.7版本正常）

- 未安装mod

<img width="425" alt="image" src="https://user-images.githubusercontent.com/16166703/230335135-21e1e2ac-7744-4a69-86cb-89b1abdab7f7.png">

- 安装1.2.8

<img width="590" alt="image" src="https://user-images.githubusercontent.com/16166703/230334861-3a5d2c1b-aa8f-4793-9574-e5eca34d7aa4.png">

1.2.7版本和1.2.8版本都存在的问题：附魔书和添加到装备上的附魔不显示等级

- 未安装mod

<img width="231" alt="image" src="https://user-images.githubusercontent.com/16166703/230335513-70bfcca0-bdad-47a8-bd07-be9b798fa42b.png">

- 安装1.2.8或1.2.7

<img width="217" alt="image" src="https://user-images.githubusercontent.com/16166703/230335547-de7cb2ca-eb69-434c-8e62-d255358234bf.png">

**Comment by KlparetlR** [comment]
我已经汇报过这个问题，模组作者的意思是，有空了解决

**Comment by 3093FengMing** [comment]
太离谱咧

**Comment by 3093FengMing** [comment]
1.2.9已解决，最近没时间sorry

**Comment by Wulian233** [comment]
> 1.2.9已解决，最近没时间sorry

所以我建议可以关掉这个issue了

**Comment by KlparetlR** [comment]
已解决，关闭
