### ISSUE TITLE
forge 1.20.1 无法加载

### ISSUE THREAD

**Issue by ddaodan** [3093FengMing/VaultPatcher#8]
安装后日志里能看到有加载信息，但是进入游戏后mod列表里没有，单机输入/vp提示未知指令
尝试编辑了一下模块文件，游戏内不生效
forge和mod都是最新版本，群里的1.3.0也是这样
![image](https://github.com/3093FengMing/VaultPatcher/assets/40017293/a33ef694-0105-4ca5-b8d7-308c54409a9f)
![image](https://github.com/3093FengMing/VaultPatcher/assets/40017293/57f69a37-3848-403b-a2df-2298058fb10e)
最小化测试
```
[
    {
        "authors": "(authors)",
        "name": "汉化",
        "desc": "汉化",
        "mods": "(mods)"
    },
    {
        "key": "Mythic",
        "value": "@神话"
    },
    {
        "key": "Drag onto gear to use",
        "value": "@放在装备上以使用"
    }
]
```
模块文件
![image](https://github.com/3093FengMing/VaultPatcher/assets/40017293/f2a66f1b-d9be-4beb-b9ad-f302e9cdd290)
游戏内不生效
![image](https://github.com/3093FengMing/VaultPatcher/assets/40017293/f0f69e24-da0c-45e1-9396-6d8bba8374a8)
日志截图，后面就没有再出现过了

**Comment by 3093FengMing** [comment]
很明显，你使用的是VP 1.2.10+（即coremod版本）。其中，coremod并不会被forge视为正常的mod并加载，所以它不会显示在mods界面中，另外coremod同样不支持命令与半匹配。如果想使用这些，请退回到1.2.10。综上，你需要了解一些有关于VP的知识。

**Comment by 3093FengMing** [comment]
如果有其他问题，请留言。否则关闭此issue

**Comment by ddaodan** [comment]
暂时没有了，有问题我在群里问吧。我再研究研究
